### ISSUE TITLE
Series 

### ISSUE THREAD

**Issue by martinstabe** [ft-interactive/starter-kit#118] opened 2017-07-06 10:45 UTC
We should add the ability to include a series package to the header.

![screen shot 2017-07-06 at 11 44 21](https://user-images.githubusercontent.com/998519/27907688-89094a92-6240-11e7-8a2e-e6762014616d.png)

**Comment by joannaskao** [comment] 2018-09-11 10:11
Duplicate of #197. Closing.

**Closed by joannaskao** 2018-09-11 10:11 UTC
